// Regenerates data/moon_data_embedded.js from the CSV files in data/.
// The embedded copy only exists so the game also works when index.html is opened
// directly from disk (file://), where browsers block fetch() of local files.
// Run after editing any CSV:   node tools/embed-csv.js
const fs = require('fs');
const path = require('path');

const FILES = [
  'moon_environment_dataset.csv',
  'moon_dust_dataset.csv',
  'earth_moon_orbital_dataset.csv',
  'moon_regions_non_polar_dataset.csv',
];

const root = path.join(__dirname, '..');
const map = {};
for (const f of FILES) map[f] = fs.readFileSync(path.join(root, 'data', f), 'utf8');
const out =
  '// AUTO-GENERATED by tools/embed-csv.js - do not edit by hand.\n' +
  '// Verbatim copies of the CSV files in data/ (the authoritative sources).\n' +
  'window.LUNA_EMBEDDED = ' + JSON.stringify(map, null, 0) + ';\n';
fs.writeFileSync(path.join(root, 'data', 'moon_data_embedded.js'), out);
console.log('Wrote data/moon_data_embedded.js (' + FILES.length + ' files)');
