// Regenerates data/moon_data_embedded.js from data/moon_environment_dataset.csv.
// The embedded copy only exists so the game also works when index.html is opened
// directly from disk (file://), where browsers block fetch() of local files.
// Run after editing the CSV:   node tools/embed-csv.js
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const csv = fs.readFileSync(path.join(root, 'data', 'moon_environment_dataset.csv'), 'utf8');
const out =
  '// AUTO-GENERATED by tools/embed-csv.js - do not edit by hand.\n' +
  '// Verbatim copy of data/moon_environment_dataset.csv (the authoritative source).\n' +
  'window.LUNA_EMBEDDED_CSV = ' + JSON.stringify(csv) + ';\n';
fs.writeFileSync(path.join(root, 'data', 'moon_data_embedded.js'), out);
console.log('Wrote data/moon_data_embedded.js (' + csv.length + ' chars)');
